FROM node:latest

ARG NEXT_PUBLIC_API_ENDPOINT
ARG NEXT_PUBLIC_GAME_SOCKET
ARG NEXT_PUBLIC_CHAT_SOCKET
ARG NEXT_PUBLIC_FT_CLIENT_ID
ARG NEXT_PUBLIC_FT_REDIRECT_URI
ARG NEXT_PUBLIC_GG_CLIENT_ID
ARG NEXT_PUBLIC_GG_REDIRECT_URI

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start" ]