name: Dr. Pong Client CI/CD

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

# permissions:
#   contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      # clean install
      - run: npm install

      # build
      - run: npm run build

      - name: Docker build & push to registry
        if: contains(github.ref, 'deploy')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }} .
          docker tag ${{ secrets.DOCKER_REPO }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

      # docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} .

      ## deploy to aws ec2 with ssh *HOST *USER_NAME *PRIVATE_KEY
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        if: contains(github.ref, 'deploy')
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker-compose down
            docker rm -f $(docker ps -qa)
            docker rmi -f ${{ secrets.DOCKER_REPO }}/dr-pong
            docker-compose up -d
